---

- name: Install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - git
   - python-pip 
   - nodejs
   - npm

- name: Install common packages with pip
  pip: name={{item}}
  with_items:
   - docopt

- name: Create sodasrv user
  action: user name=sodasrv state=present groups=dialout

- name: Create git directory
  sudo: yes
  file: path=/git state=directory owner=sodasrv group=sodasrv

- name: Clone and update repository
  sudo: yes
  sudo_user: sodasrv
  git: repo=https://github.com/chezbob/chezbob.git dest=/git

- name: Deploy chezbob config
  sudo: yes
  template: src=etc/chezbob.json.j2 dest=/etc/chezbob.json
