---

- name: Install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - python3
   - python-pip
   - python3-setuptools

- name: Easyinstall to get pip-3.2
  easy_install: executable=easy_install3 name=pip

- name: Install common packages with pip
  pip: executable=pip3 name={{item}}
  with_items:
   - docopt
