---
- name: Make sure packages are up-to date
  sudo: yes
  shell: apt-get update

- name: Install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - git
   - python3-pip

- name: Install node packages
  apt: pkg={{ item }} state=present
  with_items:
   - nodejs
   - nodejs-legacy
   - npm

- name: Install common packages with pip3
  pip: name={{item}} executable=pip3
  with_items:
    - docopt
    - flask
    - flask_jsonrpc
    - sqlalchemy
    - flask-sqlalchemy
    - flask-cors
    - requests
    - sqlalchemy-migrate
    - pyserial
    - sarge
    - bitstruct
    - cmd2
    - evdev

- name: Create sodasrv user
  action: user name=sodasrv state=present groups=dialout generate_ssh_key=yes

- name: Add host key for dev
  authorized_key: user={{ REMOTE_USER }} key="{{ lookup('file', LOCAL_USER_SSH_KEY) }}"

- name: Add host key for sodasrv
  authorized_key: user=sodasrv key="{{ lookup('file', LOCAL_USER_SSH_KEY) }}"

- name: Create git directory
  sudo: yes
  file: path=/git state=directory owner=sodasrv group=sodasrv

- name: Clean old files
  shell: rm -rf /tmp/repo /git/*

- name: Push Repository
  sudo: no
  synchronize: src={{ PATH_TO_REPO }} dest=/tmp/repo
  tags:
    - deploy

- name: Move repo in place
  shell: cp -rf /tmp/repo/*/* /git
  tags:
    - deploy

- name: Chown repo
  shell: chown sodasrv:sodasrv -R /git
  tags:
    - deploy

- name: Deploy chezbob config
  sudo: yes
  template: src=etc/chezbob.json.j2 dest=/etc/chezbob.json
