---
- name: Install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - git
   - python3-pip
   - postgresql-server-dev-9.3
   - python-dev

- name: Install node packages
  apt: pkg={{ item }} state=present
  with_items:
   - nodejs
   - nodejs-legacy
   - npm

- name: Install common packages with pip3
  pip: name={{item}} executable=pip
  with_items:
    - psycopg2

- name: Install common packages with pip3
  pip: name={{item}} executable=pip3
  with_items:
    - docopt
    - flask
    - flask_jsonrpc
    - sqlalchemy
    - flask-sqlalchemy
    - flask-cors
    - requests
    - sqlalchemy-migrate
    - pyserial
    - sarge
    - bitstruct
    - cmd2
    - evdev

- name: Create sodasrv user
  action: user name=sodasrv state=present groups=dialout generate_ssh_key=yes

- name: Add host key for dev
  authorized_key: user={{ REMOTE_USER }} key="{{ lookup('file', LOCAL_USER_SSH_KEY) }}"

- name: Add host key for sodasrv
  authorized_key: user=sodasrv key="{{ lookup('file', LOCAL_USER_SSH_KEY) }}"

- name: Create git directory
  sudo: yes
  file: path=/git state=directory owner=sodasrv group=sodasrv

- name: Clean old files
  shell: rm -rf /tmp/repo /git/*

- name: Push Repository
  sudo: no
  synchronize: src={{ PATH_TO_REPO }} dest=/tmp/repo
  tags:
    - deploy

- name: Move repo in place
  shell: cp -rf /tmp/repo/*/* /git
  tags:
    - deploy

- name: Chown repo
  shell: chown sodasrv:sodasrv -R /git
  tags:
    - deploy

- name: Deploy chezbob config
  sudo: yes
  template: src=etc/chezbob.json.j2 dest=/etc/chezbob.json

- name: Deploy Postgres pg_hba.conf (allow access to all local users)
  sudo: yes
  template: src=etc/postgresql/9.3/main/pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf

- name: Create bob database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=bob

- name: Create bob database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name=django

- name: Create bob user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=bob

- name: Create django user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=django
