---

- name: Install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - git
   - python3-pip

- name: Install node packages
  apt: pkg={{ item }} state=present
  with_items:
   - nodejs
   - nodejs-legacy
   - npm

- name: Install common packages with pip3
  pip: name={{item}} executable=pip3
  with_items:
    - docopt
    - flask
    - flask_jsonrpc
    - sqlalchemy
    - flask-sqlalchemy
    - flask-cors
    - requests
    - sqlalchemy-migrate
    - pyserial
    - sarge
    - bitstruct
    - cmd2

- name: Create sodasrv user
  action: user name=sodasrv state=present groups=dialout generate_ssh_key=yes

- name: Add host key for dev
  authorized_key: user=dev key="{{ lookup('file', '/home/dimo/.ssh/id_rsa.pub') }}"

- name: Add host key for sodasrv
  authorized_key: user=sodasrv key="{{ lookup('file', '/home/dimo/.ssh/id_rsa.pub') }}"

- name: Create git directory
  sudo: yes
  file: path=/git state=directory owner=sodasrv group=sodasrv

- name: Clean old files
  shell: rm -rf /tmp/repo /git/*

- name: Push Repository
  sudo: no
  synchronize: src=/home/dimo/projects/chezbob/chezbob dest=/tmp/repo
  tags:
    - deploy

- name: Move repo in place
  shell: cp -rf /tmp/repo/*/* /git
  tags:
    - deploy

- name: Chown repo
  shell: chown sodasrv:sodasrv -R /git
  tags:
    - deploy

- name: Deploy chezbob config
  sudo: yes
  template: src=etc/chezbob.json.j2 dest=/etc/chezbob.json

# cb_fake_hw service deployment

#- name: Deploy cb_fake_hw service template
#  sudo: yes
#  template: src=etc/init/cb_fake_hw.conf.j2 dest=/etc/init/cb_fake_hw.conf
#  tags:
#    - services

#- name: Ensure cb_fake_hw service is stopped
#  sudo: yes
#  service: name=cb_fake_hw state=stopped
#  tags:
#    - services

#- name: set service to start on boot and run
#  service: name=cb_fake_hw enabled=yes state=started
#  sudo: yes
#  tags:
#    - services
