---

- name: Install soda machine packages
  apt: pkg={{item}} state=present
  with_items:
   - postgresql
   - libpq-dev

- name: Install udev rules
  copy: src=99-cbdevices.rules dest=/etc/udev/rules.d

- name: Install required npm packages
  npm: name={{ item }} state=present global=yes
  sudo: yes
  with_items:
    - bunyan-redis-watch
