---

- name: Install soda machine packages
  apt: pkg={{item}} state=present
  with_items:
   - postgresql
   - libpq-dev
   - nodejs
   - nodejs-legacy
   - npm
  tasks:
   - initial

- name: Install udev rules
  copy: src=99-cbdevices.rules dest=/etc/udev/rules.d
  tasks:
   - initial
