---

- name: Install soda machine packages
  apt: pkg={{item}} state=present
  with_items:
   - screen
   - postgresql
   - libpq-dev
   - python3.4-dev

- name: Install GNU ARM repo
  apt_repository: repo='ppa:terry.guo/gcc-arm-embedded' state=present update-cache=yes

- name: Install GNU ARM toolchain
  apt: pkg=gcc-arm-none-eabi state=present

- name: Install required python packages
  pip: executable=pip3.4 name={{item}}
  with_items:
   - pyserial
   - flask
   - flask-jsonrpc
   - flask-cors
   - sqlalchemy
   - flask-sqlalchemy
   - psycopg2
   - json-rpc
   - requests

- name: Install udev rules
  copy: src=99-cbdevices.rules dest=/etc/udev/rules.d

- name: Install sodad upstart job
  copy: src=cb_sodad.conf dest=/etc/init/cb_sodad.conf
- name: make sure sodad is running
  service: name=cb_sodad state=started

- name: Install barcoded upstart job
  copy: src=cb_barcoded.conf dest=/etc/init/cb_barcoded.conf
- name: make sure barcoded is running
  service: name=cb_barcoded state=started

- name: Install mdbd upstart job
  copy: src=cb_mdbd.conf dest=/etc/init/cb_mdbd.conf
- name: make sure mdbd is running
  service: name=cb_mdbd state=started
