---

- name: Install soda machine packages
  apt: pkg={{item}} state=present
  with_items:
   - screen

- name: Install required python packages
  pip: executable=pip3.4 name={{item}}
  with_items:
   - pyserial
   - flask
   - flask-jsonrpc
   - flask-cors
   - sqlalchemy
   - flask-sqlalchemy
