---

# this playbook deploys the chezbob site
- hosts: soda-dev-machines
  vars:
      LOCAL_USER: "dimo"
      LOCAL_USER_SSH_KEY: "/Users/Brown/.ssh/id_rsa.pub"
      REMOTE_USER: "dev"
      PATH_TO_REPO: "/Users/Brown/Repos/chezbob"
  roles:
      - dev
      - redis
      - barcodei-server
      - barcode-server
      - mdb-server
      - vdb-server
      - soda-server
      - kiosk
